### PR TITLE
Add support for the NO_PROXY environment variable #360

### PR DESCRIPTION
**Pull request by mariaS210**
This PR is to implement issue #360 to  add support for NO_PROXY environment variable.

Added documentation string to environment_variables.md
Added option to pass no_proxy in Client
Added tests, hopefully for all branches (I might have been a bit lost in codecov)

Please let me know if I missed anything, and suggest improvements.
Thank you

### CODE REVIEW

**Comment by sethmlarson** [comment]
This code is different if we were to move the proxy resolution into an `HTTPProxy` instance that wraps a `ConnectionPool` rather than doing it's own dispatch. I have some changes locally that might want to land before this actually, it'll be easier to implement.

**Comment by sethmlarson** [comment]
Maybe you should change this PR into logic that takes a URL and then decides `True`/`False` whether that URL should be proxied. Then I can re-use that component. :)

**Comment by mariaS210** [comment]
> This code is different if we were to move the proxy resolution into an `HTTPProxy` instance that wraps a `ConnectionPool` rather than doing it's own dispatch. I have some changes locally that might want to land before this actually, it'll be easier to implement.

Should I wait with this PR until you push your local changes, then see how to integrate the logic  into HTTPProxy?

**Comment by sethmlarson** [comment]
@mariaS210 If you'd like you can open a separate PR implementing the component I've described above then come back to this PR later. :)

**Comment by sethmlarson** [comment]
Closed in favor of #472.

**Pull request closed without merging**
