### PR TITLE
Remove all unused self params and convert to staticmethods

### PR DESCRIPTION
**Pull request by felix-hilden**
From the discussion in #1152, this PR converts all methods with an unused `self` to staticmethods.

This was not exactly agreed upon, so feel no obligations towards merging this if it's not to your taste. There is a case to be made for ignoring insignificant changes to reduce noise and keep history, but I do feel that small details add up. Anyway, thanks for having a look!

### CODE REVIEW

**Comment by tomchristie** [comment]
I'm a bit lukewarm towards doing this throughout. I get that we *could*, and that the methods would be more tightly scoped if we did, but also it's not terrible that Python code often uses standard methods as a name-spacing, even when they are not necessarily also state changing.

Having said that, I've not taken a proper review over it, so it's possible that it makes good sense in places.

**Comment by felix-hilden** [comment]
I see! Lukewarm's no good, is it 😄 I have not considered that one could want an unused self, but that's probably my inexperience, as I don't quite understand what it means to use standard methods as a name-spacing. Nevertheless, this is here for you to accept or reject. I'd be happy to make any changes to include only a subset in suitable places if you find it appropriate!

**Comment by florimondmanca** [comment]
I guess my take on this is that all these methods are `@staticmethod`-convertible mostly _by accident_. If we did need to access class state we'd need to convert them back again to standard methods. "Practicality beats purity", I guess. So while I appreciate you proposing these changes, I'm also a bit "_meh_" on going forward with these. 😅

**Comment by felix-hilden** [comment]
Fair enough!

**Pull request closed without merging**
