### PR TITLE
Preserve header casing

### PR DESCRIPTION
**Pull request by tomchristie**
Refs #538

This pull request would change `Headers` to be a case-preserving but case-insenstive mutli dict.

This would resolve HTTP header casing in the sync case, although not for the async case. (Since `h11` currently lowercase-normalizes headers in both directions)

### CODE REVIEW

**Comment by florimondmanca** [comment]
I merged `master` back in here just in case a week's worth of changes might break anything, though I don't think it will…

**Comment by tomchristie** [comment]
So it occured to me that we ought to ensure that `.keys()` returned lowercased variants.

What's nice about that is we still have full header casing available in the `repr`, and available if users *really* want to see it in the raw header bytes, but otherwise we're keeping things properly constrained and exposing a strictly lowercase style.

So...

* `response.headers[X]` - Case insensitive lookups.
* `dict(response.headers)` - Returns lowercased variants, ensuring users can't easily write accidentally case-sensitive code.
* `repr(response.headers)` - Displays actual case variants.
* `response.headers.raw` - Access the list of byte tuples, in raw actual case.

**Comment by tomchristie** [comment]
Might take another pass onto this at some point.

**Comment by valiant1x** [comment]
Is it intended that async usage of http1.1 is still lowercasing all headers? In Python 3.8.2 with httpx 0.12.1 this is the behavior I see. How can we preserve proper header casing in HTTP/1.1 with `async`? @tomchristie @florimondmanca

**Pull request closed without merging**
