### PR TITLE
Drop HSTS Preloading

### LINKED ISSUE #896: Document HSTS is still honored if allow_redirects=False
I tried to disable the redirection with latest httpx but it is always redirection the URL:

```python
>>> import httpx
>>> r = httpx.head("http://www.python.org",  allow_redirects=False)
>>> r.url
URL('https://www.python.org')
```

status code is also 200 and not 301 as expected.

### LINKED ISSUE #1102: Consider dropping HSTS preloading
Prompted by https://github.com/encode/httpx/issues/1025#issuecomment-661269344

Issues like #1025 should prompt us to reconsider whether using HSTS preloading from a server-side client (introduced via #151) is a sensible thing to do at all.

Key points of reasoning here:

- While it mimics the way browsers behave, and [hstspreload](https://github.com/sethmlarson/hstspreload) is a super valuable library, from a UX perspective it can lead to ambiguous behaviors (#896) and cases when you _really_ don't want HSTS preload to kick in (like in #1025).
- Crucially, from #124 it seems that HSTS preloading was introduced as a way to tackle "schema-less URLs". As of today HTTPX _requires_ a schema on URLs, so if it was the initial motivation then it is now irrelevant. Besides, we can assume that developers are generally very aware of their choices to use `http://` vs `https://` on the server-side (as opposed to browser users just entering the domain name without a schema).

Some options are:

- Add a toggle so that HSTS preload becomes opt-in or opt-out.
- Drop HSTS functionality entirely.

Given all the context points above, we might want to just go with option 2).

### PR DESCRIPTION
**Pull request by florimondmanca**
Maybe? See the rationale in #1102

Fixes #1102, closes #896

Essentially:

```python
>>> import httpx
>>> r = httpx.get('http://www.paypal.com')  # -> Now kept over HTTP rather than forced to HTTPS.
```

I suppose if we want to move forward with this we'd want it in 0.14, rather than 1.0, since it might be a small breaking change?

Since this was an always-on feature not controlled by any options, I can't think of a smooth deprecation path, but any ideas welcome!

### CODE REVIEW

**Comment by StephenBrown2** [comment]
Perhaps `hstspreload`ing could be kept, but not enforced by default, and a `TRACE` or `DEBUG` message emitted when a host is found on the list and doesn't match the preferred scheme?

**Comment by tomchristie** [comment]
So, it's a wooly issue, but I think yes let's get this in and treat HSTS as appropriate as a browser feature, but not *necessarily* desirable in client library.

**Comment by StephenBrown2** [comment]
I would hate for the great work in the `hstspreload` module to go unused. Would it be good to include a brief mention in the docs for those that do want that functionality?

**Comment by florimondmanca** [comment]
I'm trying to think of how people could enable this without us having to support it in core with a flag…

I don't think a custom transport would be the way to go, since transports don't deal with client logic like "optionally modify the request URL".

Probably more like a client subclass, then…?

```python
import httpx
import hstspreload

class HSTSPreloadMixin:
    def build_request(self, *args, **kwargs):
        request = super().build_request(*args, **kwargs)

        url = request.url

        if (
            url.scheme == "http"
            and hstspreload.in_hsts_preload(url.host)
            and len(url.host.split(".")) > 1
        ):
            port = None if url.port == 80 else url.port
            request.url = url.copy_with(scheme="https", port=port)

        return request

class AsyncClient(HSTSPreloadMixin, httpx.AsyncClient):
    pass

class Client(HSTSPreloadMixin, httpx.Client):
    pass
```

Incidentally I think this could also fit in a "middleware" kind of concept (#345), but that's definitely not something we'll have 1.0.

**Comment by StephenBrown2** [comment]
Possibly, but I was thinking of and even simpler approach/demonstration:

`util.py`
```py
from typing import Union

from httpx import URL
from hstspreload import in_hsts_preload

def check_hsts(url: Union[str, URL]):
    if isinstance(url, str):
        url = URL(url)
    if in_hsts_preload(url.host):
        return url.copy_with(scheme="https")
    return url
```
...
`main.py`
```py
import httpx

from util import check_hsts

with httpx.Client() as client:
    client.get(check_hsts(the_url))
```
or with `base_url`:
```py
with httpx.Client(base_url=check_hsts(the_url)) as client:
    client.get(path)
```

**Pull request merged**
