### PR TITLE
chore: add config for pointing to Gitter chat

### PR DESCRIPTION
**Pull request by Midnighter**
This configuration enables an entry in the issue template picker that points to the Gitter channel instead.

### CODE REVIEW

**Comment by Midnighter** [comment]
black had an update last night and now annoyingly formats code differently. I don't think it makes sense to handle that in this PR.

**Comment by tomchristie** [comment]
Great. How about we keep that *changes* this introduces a bit minimal, so instead of this...

0ED6C464-8EEB-4897-9C07-C39EFB69116E

We could instead drop the “Question” issue template, and instead replace it with a “Question” external link, with exactly the same text. Simply “Ask a question”.

Also let’s keep the “Open a blank issue” as it is for now.

**Comment by Midnighter** [comment]
Okay, shall I do the same for https://github.com/encode/uvicorn/pull/768 then?

**Comment by tomchristie** [comment]
I reckon so, yup.

**Review by tomchristie — APPROVED** [review]
Great, let's give it a go.

**Comment by tomchristie** [comment]
Fantastic, I think the new flow looks great!

**Pull request merged**
