### PR TITLE
pass on cert, verify, timeout, trust_env to Client

### PR DESCRIPTION
**Pull request by AtomsForPeace**
Think this is what's needed for #505

I'd love to add a test for it but couldn't think of any sensible way of doing. Tried messing around with mocking the Client object and seeing the attributes that were set in the request function call but didn't pan out as hoped.

Any suggestions for tests?

I'd be happy to add one.

Let me know if I should remove timeout, cert, verify and leave only trust_env.

### CODE REVIEW

**Comment by AtomsForPeace** [comment]
Hmmm, I see that mypy is failing.

Would it possibly be better to have the defaults for timeout and trust_env the same in request as they are in Client?

Client has trust_env: bool = True but request has trust_env: bool = None.

That would solve the type issue.

**Comment by tomchristie** [comment]
> Hmmm, I see that mypy is failing.

Right - this PR should also change the signatures in `api.py` so that the defaults match the defaults we're using on `Client`. That ought to resolve the issue.

Eg. we want `trust_env: bool = True` in our `api.py` signatures.

**Comment by tomchristie** [comment]
Oh right, I'd skimmed this. Yes your observation here is spot on...

> Would it possibly be better to have the defaults for timeout and trust_env the same in request as they are in Client?

😃 Absolutely, yes. Go for it!

**Comment by AtomsForPeace** [comment]
Ready to merge?

**Comment by tomchristie** [comment]
Thanks for having put in the work here. Incorperated into https://github.com/encode/httpx/pull/544

**Pull request closed without merging**
