### PR TITLE
More robust check for upload files in binary mode

### PR DESCRIPTION
**Pull request by lkuchenb**
This is a minor patch proposal fixing fixing an issue with a recently introduced check for binary file objects in multipart uploads. The currently used check
https://github.com/encode/httpx/blob/f1157dbc4102ac8e227a0a0bb12a877f592eff58/httpx/_multipart.py#L125-L128
misses out on file objects that read and write byte-like objects, but have the `mode` attribute set to `r` such as [ZipFile.open()](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open) which is binary-only.

### CODE REVIEW

**Comment by lkuchenb** [comment]
The `StringIO` check is now somewhat obsolete, I've changed the order so that the more specific test comes first, but they could probably also be merged into one with a meaningful combined message.

**Comment by tomchristie** [comment]
do we think it's worth adding an extra test for this case or we happy to accept the pr as-is?

**Review by tomchristie — APPROVED** [review]

**Comment by tomchristie** [comment]
Thanks!

**Comment by lkuchenb** [comment]
Thanks for the review @tomchristie - I didn't think covering this with a test would make much sense since the test would involve intentionally making false assumptions about standard library behavior, not something one would typically want to test IMHO.

**Pull request merged**
