### PR TITLE
Add backend param to ASGIDispatcher

### LINKED ISSUE #247: Make ASGI dispatcher asyncio-agnostic
*Note: this issue breaks apart steps originally taken in #217.*

The ASGI dispatcher currently relies on asyncio-specific APIs to perform various operations, which is a blocker towards supporting alternative concurrency backends.

We want to make sure all of the I/O inside `ASGIDispatch` goes through the backend instead.

This will need the following, most of which can be tackled in independant PRs:

- [x] #257 Hard-code `self.backend = AsyncioBackend()` on `ASGIDispatch` to be able to iteratively defer asyncio-specific APIs to the backend.

- [x] #257 Introduce a queue-like interface:

```python
class BaseQueue:
    async def get(self): ...
    async def put(self, value: typing.Any): ...
```

along with a `.create_queue()` method on `ConcurrencyBackend`, to be used instead of/within the `BodyIterator`.

(For trio we'll probably need to add a `.close()` method as well, but that can be confirmed and tackled in due time.)

- [x] #260 Introduce a `BaseEvent` interface:

```python
class BaseEvent:
    def set(self): ...
    def is_set(self): ...
    async def wait(self): ...
```

along with a `.create_event()` method on `ConcurrencyBackend` to abstract `asyncio.Event()`.

- [x] #261 Remove usage of loop.create_task() via the background manager interface.

- [ ] Lastly, turn the hard-coded `backend` into a parameter. Make sure it is optional and we use `AsyncioBackend` as a default.

### PR DESCRIPTION
**Pull request by florimondmanca**
Fixes #247

### CODE REVIEW

**Comment by sethmlarson** [comment]
Thanks @florimondmanca!

**Comment by cansarigol** [comment]
Hi, it was merged but is there any obstacle for this:`backend: ConcurrencyBackend = AsyncioBackend()` . Just to narrow down #272

**Comment by sethmlarson** [comment]
Yes, you don't want to use mutable objects as defaults for function parameters because instead of getting a new copy on every call it'll use the same instance.

**Comment by cansarigol** [comment]
ah sorry 👍

**Pull request merged**
