### PR TITLE
Check disconnections on connection reacquiry

### PR DESCRIPTION
**Pull request by tomchristie**
Check for connection aliveness on re-acquiry from connection pool.

Superseeds #143

Great work on this @yeraydiazdiaz! There was a last little bit of extra cleanup on the connection pool handling that we can do now, which it made sense for me to pick up. I think we're good to go on this one now.

### CODE REVIEW

**Comment by tomchristie** [comment]
I've pulled in a last little bit of extra work on top of this in #145 which I think is now good to go.

One particularly interesting point from @njsmith, here https://github.com/encode/httpx/pull/143#issuecomment-515202982

> There's StreamReader.at_eof, but that will fail if the HTTP server is polite and sends a 408 Request Timeout before it closes the connection.

Okay, that's an *interesting* case. 😑

I'd suggest we start by getting this change in as it stands. We can the confirm if we need to finesse the specific `is_connection_dropped()` implementation details as a separate improvement on top of this.

**Comment by sethmlarson** [comment]
Should we open a separate issue to handle the 408 case?

**Comment by tomchristie** [comment]
Yeah, defo. On it.

**Comment by tomchristie** [comment]
Released as 0.6.8

**Pull request merged**
