### PR TITLE
Support context manager in Response object

### PR DESCRIPTION
**Pull request by Zheaoli**
# Summary

For now, the context manager has been supported in requests lib, FYI https://github.com/psf/requests/blob/main/requests/models.py#L706-L711

So the people can use it more easy like

```python
with requests.get('https://httpbin.org/get') as r:
        # Do things with the response here.
        r.raise_for_status()
```

So I think it would be great to support context manager in httpx

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by tomchristie** [comment]
Non-streaming case...

```python
r = httpx.get('https://httpbin.org/get')
```

Streaming case...

```python
with httpx.stream('GET', 'https://httpbin.org/get') as r:
        # Do things with the response here.
        r.raise_for_status()
```

**Comment by Zheaoli** [comment]
> Member

I know, but the requests lib keeps the stream response and non-stream response to reach a consensus style. I think it's better to keep the API consensus.

**Comment by tomchristie** [comment]
> I think it's better to keep the API consensus.

would you like to open a discussion for this proposal?

**Comment by Zheaoli** [comment]
> > I think it's better to keep the API consensus.
> 
> would you like to open a discussion for this proposal?

Sure

**Comment by Zheaoli** [comment]
https://github.com/encode/httpx/discussions/2717

**Pull request closed without merging**
