### PR TITLE
Add profiler tool

### PR DESCRIPTION
**Pull request by florimondmanca**
I created https://github.com/florimondmanca/httpx-profile and @sethmlarson suggested I bring it in here. :)

Running it has uncovered some interesting insights already. For example, inside a `client.get()`:

- We're spending 30% (!) of the time looking up the `.netrc` login — we should probably cache that info once we have it?
- 13% is spent in `Client.build_request()` (the blue rectangle on the right), mostly in `merge_url()` — our `rfc3986` seems to be slowing us down here.

Screenshot 2019-09-20 at 23 40 02

We have some performance issues up such as #262, so this tool could be useful for all sorts of performance things.

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
This is awesome @florimondmanca, thanks for putting this together. 🌟 

As a somewhat related node, in the past I've used [`pytest-benchmark`](https://pytest-benchmark.readthedocs.io/en/stable/) and wrote a different test suite to monitor the performance of the code. It first occured to me we could combine it with profiling but this solution seems more focused for finding what is causing the performance problem is rather than detecting changes on it.

I might take a stab at benchmark testing if it sounds useful.

**Comment by florimondmanca** [comment]
That does sound interesting @yeraydiazdiaz!

This tool is indeed more geared towards identifying performance issues rather than measuring execution speed. I'll reword things here a bit to move uses of the word "benchmark" altogether.

**Comment by florimondmanca** [comment]
Hmm, so `pytest-benchmark` made me think that maybe there were pytest plugins to benchmark the test code as it runs, potentially resulting in a much simpler setup for us.

Turns out, there is one: [`pytest-profiling`](https://pypi.org/project/pytest-profiling/). I'm having issues having it generate the SVG file though, and the project hasn't seen a commit since last May. I guess this custom tool is simple enough that we can afford to maintain it ourselves.

**Comment by florimondmanca** [comment]
I also pushed some polishing commits — the supporting surver now runs automatically in the background.

Example output:

```console
$ httpxprof run async                                    
Server started at 127.0.0.1:8123.
100%|███████████████████████████████████████████████████████████████████████████| 1000/1000 [00:03<00:00, 277.89it/s]
Stopping server...
```

**Comment by sethmlarson** [comment]
@florimondmanca What are your thoughts on pointing our linting (maybe not mypy) at the `tools/` directory as well? :)

**Comment by florimondmanca** [comment]
@sethmlarson I added that in the latest commit. :) Is this good to merge?

**Pull request merged**
