### PR TITLE
Use utf-8-sig for decoding to handle BOM

### PR DESCRIPTION
**Pull request by fredrike**
The starting point for contributions should usually be [a discussion](https://github.com/encode/httpx/discussions)

Simple documentation typos may be raised as stand-alone pull requests, but otherwise
please ensure you've discussed your proposal prior to issuing a pull request.

This will help us direct work appropriately, and ensure that any suggested changes
have been okayed by the maintainers.

- [ ] Initially raised as discussion #...

### CODE REVIEW

**Comment by tomchristie** [comment]
Interesting. I didn't know about the `utf-8-sig` codec.

* Is it documented somewhere?
* Are you able to point to an example URL with content that includes a leading BOM?

**Comment by fredrike** [comment]
Here is a short discussion about `utf-8-sig` https://www.howtosolutions.net/2019/04/python-fixing-unexpected-utf-8-bom-error-when-loading-json-data/

Official doc: https://docs.python.org/3/library/codecs.html#module-encodings.utf_8_sig

"Broken" page: https://service.karlskrona.se/FileStorageArea/Documents/bad/1.1/swimAreas.geojson and https://service.karlskrona.se/FileStorageArea/Documents/bad/swimAreas.json

**Comment by tomchristie** [comment]
Checking the test run I can see that there's currently a linter failure... https://github.com/encode/httpx/pull/1724/checks?check_run_id=2942212371

You'll want to run `scripts/lint` in order to resolve this.

**Comment by tomchristie** [comment]
Can you provide some example code that you're using?...

As I was reviewing this I was reminded that `r.json()` actually calls the `guess_json_utf` utility function, which accounts for BOM markers, and is more complex/awkward than just using `utf-8-sig`.

https://github.com/encode/httpx/blob/ab64f7c41fc0fbe638dd586fecf0689c847109bb/httpx/_utils.py#L103

**Comment by fredrike** [comment]
> Can you provide some example code that you're using?...
> 
> As I was reviewing this I was reminded that `r.json()` actually calls the `guess_json_utf` utility function, which accounts for BOM markers, and is more complex/awkward than just using `utf-8-sig`.
> 
> https://github.com/encode/httpx/blob/ab64f7c41fc0fbe638dd586fecf0689c847109bb/httpx/_utils.py#L103

Smart, I'll write a short example but think that the json function is a better solution.

I faced this in home-assistant and opened a case there but realized that it might be better here. But usin the httpx json function is probably the best for all https://github.com/home-assistant/core/pull/52257.

**Pull request closed without merging**
