### PR TITLE
Add 'fork' to auto backend

### PR DESCRIPTION
**Pull request by tomchristie**
Seems that we don't have coverage for this yet.

### CODE REVIEW

**Comment by tomchristie** [comment]
No sweat! 😃

**Comment by tomchristie** [comment]
Incidentally, #612 actually means we *won't* end up needing fork or a background manager *at all*.

**Comment by florimondmanca** [comment]
Is this actually causing errors? Curious about why we didn't catch this… Probably worth refactoring our test setup to test all possible backends - right now I believe we force `backend=AsyncioBackend()` and `backend=TrioBackend()`, so don't cover the `auto` part nor passing a string.

**Comment by tomchristie** [comment]
Yes - causing a `NotImplementedError` when using HTTP/2.

We'll probably want to test using `backend='auto'`, `backend='trio'`, `backend='asyncio'`, but there may be a bit of rejigging to do wrt. running the test server.

**Comment by florimondmanca** [comment]
@tomchristie I'm taking a look at it. :-)

**Pull request merged**
