### PR TITLE
Keep Proxy._build_auth_header as a private method

### PR DESCRIPTION
**Pull request by tomchristie**
Tiny refactoring. `Proxy._build_auth_header` should be a private method.

### CODE REVIEW

**Comment by jcugat** [comment]
Small note, might be worth moving the code from `BasicAuth.build_auth_header` and `Proxy._build_auth_header` to a utils function (since it's essentially the same).

**Comment by florimondmanca** [comment]
@tomchristie - Should we add @jcugat to the Maintainers (don't have permissions to do this myself) so his reviews are well accounted for by the GitHub UI checks? :-)

**Comment by tomchristie** [comment]
@florimondmanca @jcugat 💯 👍  Good call. Done.

**Comment by florimondmanca** [comment]
@tomchristie Not sure which comment you were answering to but I don't see Josep in the members list yet: https://github.com/orgs/encode/teams/maintainers/members

**Pull request merged**
