### PR TITLE
Typing: enable warn_return_any

### PR DESCRIPTION
**Pull request by mjpieters**
Part of the work for #2436

### CODE REVIEW

**Review by tomchristie — APPROVED** [review]
Seems reasonable, yup.

**Comment by tomchristie** [comment]
Looks like we're [missing one case here](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:20)...

```shell
Run scripts/check
[11](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:12)
+ ./scripts/sync-version
[12](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:13)
CHANGELOG_VERSION: 0.23.1
[13](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:14)
+ black --check --diff --target-version=py37 httpx tests
[14](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:15)
VERSION: 0.23.1
[15](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:16)
All done! ✨ 🍰 ✨
[16](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:17)
60 files would be left unchanged.
[17](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:18)
+ flake8 httpx tests
[18](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:19)
+ mypy httpx tests
[19](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:20)
tests/test_content.py:73: error: Returning Any from function declared to return "bytes"  [no-any-return]
[20](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:21)
Found 1 error in 1 file (checked 60 source files)
[21](https://github.com/encode/httpx/actions/runs/3582031891/jobs/6025779338#step:5:22)
Error: Process completed with exit code 1.
```

**Review by tomchristie — CHANGES_REQUESTED** [review]
Needs one case fixing in `test_content.py`.

**Comment by mjpieters** [comment]
> Needs one case fixing in `test_content.py`.

I'll take a look, I don't quite know why locally that was not being flagged before, but I do see it now that I rebased.

**Pull request merged**
