### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
## Description

Hi :wave:, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some [interesting code quality](https://deepsource.io/gh/akshgpt7/httpx/) issues that can improve the general code quality and performance here.
This PR fixes a few of the issues detected.

## Summary of changes
- Iterate directly over dictionary instead of calling `dict.keys()`.
- Refactor usage of `assert` outside tests.
- Refactor unnecessary `elif`/`else` after `raise` and `break`. 
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

### CODE REVIEW

**Comment by euri10** [comment]
interesting to see the CI fail on this :lobster:

**Comment by akshgpt7** [comment]
@euri10 
It seems to be failing on the Coverage.
Any heads up on how to go about it would be really helpful~
I'll rebase and squash the commits.

**Comment by StephenBrown2** [comment]
Add a test that covers line 191, i.e. one that makes "scheme" something valid that is not "digest" and verifies an AssertionError is raised.

**Comment by StephenBrown2** [comment]
Add a test that covers line 191, i.e. one that makes "scheme" something valid that is not "digest" and verifies an AssertionError is raised.

**Comment by florimondmanca** [comment]
@akshgpt7 Hey!

Thanks for opening this. :) Just to clarify that we're happy to go with any sensible tweaks, but we'd need to drop the `.deepsource.toml` file before merging. Committing to using a service like DeepSource should be a separate community decision (my personal position is a pragmatic "not really interested; we've been doing nicely without", but happy to discuss with anyone).

**Comment by florimondmanca** [comment]
Also — I'd add that although you are free to promote this service, personally I would have appreciated a clearer messaging that this is indeed a promotional PR for an external service you seem to be working at. Eg something along the lines of "Hey, I work at XYZ, I ran our software and found some improvements, opening this PR so you can assess if our service is right for you; happy to provide the tweaks separately otherwise". The semi-implicit wording and mixing service-specific changes with possibly legit tweaks leaves a mixed impression of "forcing it" for me, and as a maintainer tends to trigger my defensive side. 😁 Hope this can be useful feedback!

**Comment by akshgpt7** [comment]
@florimondmanca Thanks a lot for your feedback. Really appreciate it :)

**Comment by StephenBrown2** [comment]
I'm also a bit suspicious of some of the "issues" found, several appear to be non-issues or actually wrong recommendations. I haven't gone through all of them, but in particular the [Bad async magic method](https://deepsource.io/gh/akshgpt7/httpx/issue/PTC-W0045/occurrences), [`yield` would not work as expected in the magic method](https://deepsource.io/gh/akshgpt7/httpx/issue/PTC-W0059/occurrences), and [Invalid sequence index found](https://deepsource.io/gh/akshgpt7/httpx/issue/PYL-E1126/occurrences) for example are incorrect IMO and the descriptions don't provide too much in the way of help.

Further investigation and explanation are required.

**Pull request closed without merging**
