### PR TITLE
Remove deprecated 'proxies' parameter.

### PR DESCRIPTION
**Pull request by tomchristie**
I've created `version-1.0` branch so that we can incrementally merge 1.0 PRs prior to a release.

I'm going to start by issuing some obvious pull requests that remove API that's already been deprecated.
This pull request deals with removing the `proxies=...` parameter, which has been deprecated in favor of `proxy=...`, with `mount=...` used for more complex configurations.

### CODE REVIEW

**Comment by karpetrosyan** [comment]
I remember I also left the tests. We need to remove them as well. Do you need any help?

**Comment by karpetrosyan** [comment]
Also, I suggest turning on CI for branches that start with 'version-'.

**Comment by tomchristie** [comment]
Hrm, either I got #3318 wrong, or else it isn't effecting outstanding PRs.

**Comment by karpetrosyan** [comment]
> Hrm... either I got #3318 wrong, or else it isn't effecting outstanding PRs.

We merged it into the master, not version-1.0:)
In this branch we do not have any CI

**Pull request merged**
