### PR TITLE
Support max_redirects per request

### PR DESCRIPTION
**Pull request by Pliner**
# Summary

Hi,

Sorry for not opening a discussion before. It is a tiny change and I do hope you find it useful and reasonable. 

PR aims to allow setting max_redirects on a request basis as it is already possible for forward_redirects. 

PS [aiohttp allows](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L339) to set this on a request basis as well. 

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Review by musale — APPROVED** [review]
Looks good to me.

**Comment by tomchristie** [comment]
If anything the PR is (to me) a useful prompt suggesting that a neater API would be if `max_redirects` wasn't a top-level setting, and was instead part of the `limits=...` configuration.

How would you feel about us closing this off, and going through the "design discussions first, please" route?

**Comment by musale** [comment]
> If anything the PR is (to me) a useful prompt suggesting that a neater API would be if `max_redirects` wasn't a top-level setting, and was instead part of the `limits=...` configuration.
> 
> How would you feel about us closing this off, and going through the "design discussions first, please" route?

That sounds fair to me :)

**Comment by Pliner** [comment]
> If anything the PR is (to me) a useful prompt suggesting that a neater API would be if `max_redirects` wasn't a top-level setting, and was instead part of the `limits=...` configuration.
> 
> How would you feel about us closing this off, and going through the "design discussions first, please" route?

Sure, thanks!

**Pull request closed without merging**
