### PR TITLE
Handle bare env proxy hostname gracefully

### LINKED ISSUE #1082: Should we support bare hostnames in `ALL_PROXY`,`HTTP_PROXY`, `HTTPS_PROXY`?
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am a new user for httpx, and I just install it, then try to run it in python REPL.
I type `httpx.get('https://www.github.com')`  and then got the "No scheme included in URL".
So I try to debug it, and finally I found that because I set the `export ALL_PROXY=127.0.0.1:7890` in the shell, the proxy does not have a scheme. 
This proxy set is correct for when I use curl、brew and many other programe, So it should also work fun in httpx?
for any other reason httpx must have the scheme, I think it should prompt "a proxy set error" at least.

### Debugging material

```
~/projects » python3                                                                                                       hejl@hejldeIMAC
Python 3.8.4 (default, Jul 14 2020, 02:58:48) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import httpx
>>> httpx.get("https://www.github.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/httpx/_api.py", line 159, in get
    return request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_api.py", line 83, in request
    with Client(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 467, in __init__
    proxy_map = self.get_proxy_map(proxies, trust_env)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 87, in get_proxy_map
    return {
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 88, in <dictcomp>
    key: Proxy(url=url)
  File "/usr/local/lib/python3.8/site-packages/httpx/_config.py", line 335, in __init__
    url = URL(url)
  File "/usr/local/lib/python3.8/site-packages/httpx/_models.py", line 90, in __init__
    raise InvalidURL("No scheme included in URL.")
httpx._exceptions.InvalidURL: No scheme included in URL.
```

### Environment

- OS:  MacOS
- Python version: 3.8.4
- HTTPX version: 0.13.3
- Async environment: no
- HTTP proxy: yes  `127.0.0.1:7890`
- Custom certificates: no

### PR DESCRIPTION
**Pull request by j178**
Follow up on #1118, Closes #1082

### CODE REVIEW

**Comment by tomchristie** [comment]
@j178 Have invited you to the maintainers team. 👍
If you accept you'll be able to merge reviewed PRs, and you own approval reviews will allow a PR to be merged.

**Comment by j178** [comment]
@tomchristie Wow, thanks!

**Comment by j178** [comment]
@tomchristie Sorry tom, I have not received the invitation yet 😢

**Comment by florimondmanca** [comment]
@tomchristie Likewise not sure if @jcugat had been successfully invited to the team (see https://github.com/encode/httpx/pull/1011#issuecomment-636493420) 😅 Miss clicking the "Send invite" button, or something similar?

**Pull request merged**
