### PR TITLE
Pin httpcore==0.8.3

### PR DESCRIPTION
**Pull request by yeraydiazdiaz**
https://github.com/encode/httpx/issues/943 maybe...

### CODE REVIEW

**Comment by yeraydiazdiaz** [comment]
Running tests one more time, for safety

**Comment by yeraydiazdiaz** [comment]
Looks like we have a winner...

I guess we should merge this to unblock other PRs?

**Comment by tomchristie** [comment]
And *ping*. A failure against 0.8.3 too.

**Comment by tomchristie** [comment]
So ATM we've no evidence that the flakiness is an `httpcore` regression, but if it was it'd be something introduced in 0.8.3 or prior.

**Comment by yeraydiazdiaz** [comment]
Yep, makes sense I could not see anything that would explain this. 👍

**Pull request closed without merging**
