### PR TITLE
Set message attribute in all exceptions

### LINKED ISSUE #1252: Docs incorrectly reference `HTTPError.message` attribute
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The documentation indicates that message field can be used in the HTTPError:
https://github.com/encode/httpx/blob/master/httpx/_exceptions.py#L54
```
    try:
        response = httpx.get("https://www.example.com")
        response.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"HTTP Exception for {exc.request.url} - {exc.message}")
```
But there is not such field:
```
AttributeError: 'HTTPStatusError' object has no attribute 'message'
```

### To reproduce

Execute the example from the doc

### Expected behavior

Print the string without raising any exceptions

### Actual behavior

AttributeError is raised

### Possible fixes

1. Update the documentation to use `str(exc)` instead of `exc.message`
or
2. Set `self.message` field in HTTPError

### PR DESCRIPTION
**Pull request by tsotnikov**
Fixes #1252

### CODE REVIEW

**Review by magiskboy — APPROVED** [review]

**Review by florimondmanca — COMMENTED** [review]
Heya!

I think I'm in line with @tomchristie's comment here - https://github.com/encode/httpx/issues/1252#issuecomment-686761772

Given that we don't expose an `exc.message` attribute in any other exception class, we should probably just update the docstring here to say:

```python
print(f"HTTP Exception for {exc.request.url} - {exc}")
```

**Comment by tsotnikov** [comment]
From @tomchristie comment I understood that we prefer to set and expose `exc.message` as message is mandatory in HTTPError.

**Comment by florimondmanca** [comment]
You're right, I misread his initial recommendation. Well in that case I'll have to disagree, since given that we don't expose a `.message` attribute anywhere else, I do think just updating the docs is the best low-touch approach. :-)

**Comment by tsotnikov** [comment]
Ok, so we have two alternatives or add "message" attribute to all base exception or fix the doc.

Feel free to choose between this PR and #1255  and close whichever you discard

**Comment by tomchristie** [comment]
Thanks all, neat resolution to this one. 👍

**Pull request closed without merging**
