### PR TITLE
Warn a ResourceWarning when AsyncClient hasn't been closed (#871)

### PR DESCRIPTION
**Pull request by cdeler**
I added a warning in the `__del__` function inside the `AsyncClient` (I'm not sure if we can do more)

### CODE REVIEW

**Comment by cdeler** [comment]
Reviewing the PR please check this build https://github.com/encode/httpx/pull/1191/checks?check_run_id=997511344

I don't know why it failed, after that I just touched one of the files, force-pushed my branch and the test went back to the normal.

**Comment by cdeler** [comment]
I introduces a new piece of changes in https://github.com/encode/httpx/pull/1191/commits/1fdab27a9e6a6e99e8a3579aa787c42a0a2007ae

As soon as `aclose()` has set `_is_closed = True`, we cannot send any requests or call `aclose` again.

**Comment by felix-hilden** [comment]
Now this PR is doing two things: warning on an unclosed `AsyncClient` and raising errors on making requests with a closed client. As Tom pointed out in Gitter, it would be nice to separate them. Additionally, I think that the call restrictions ought to apply to the synchronous `Client` as well.

A small design consideration for the other PR, but I'll mention it already because you started implementation: a simple check and error could be more easily implemented and maintained as a decorator.
```python
from typing import Callable
from functools import wraps

def check_not_closed(method: Callable):   # or a better name :D
    @wraps(method)
    def wrapper(self, *args, **kwargs):
        if self.is_closed:
            raise RuntimeError('Cannot use a closed client!')
        return method(self, *args, **kwargs)
    return wrapper

class Client:
    @check_not_closed
    def send(self, request):
        ...
```
Or if the message should change, a parameterised decorator. It's a pretty small thing to extract, but in my humble opinion, could be worth it.

**Comment by cdeler** [comment]
> Now this PR is doing two things: warning on an unclosed AsyncClient and raising errors on making requests with a closed client. As Tom pointed out in Gitter, it would be nice to separate them
Sure, I was out of keyboard, now I am to do that. I'm closing the current PR

> A small design consideration for the other PR, but I'll mention it already because you started implementation: a simple check and error could be more easily implemented and maintained as a decorator.
Java side of my brain want to introduce new interface a-la "closable"

**Comment by cdeler** [comment]
Close to split the PR into 2 parts

**Pull request closed without merging**
