### PR TITLE
Version 0.27.1

### PR DESCRIPTION
**Pull request by mbeijen**
As suggested in https://github.com/encode/httpx/pull/3139#issuecomment-2299677531

## Added

* Support for `zstd` content decoding using the python `zstandard` package is added. Installable using `httpx[zstd]`. (#3139)

### Fixed

* Improved error messaging for `InvalidURL` exceptions. (#3250)
* Fix `app` type signature in `ASGITransport`. (#3109)

### CODE REVIEW

**Comment by tomchristie** [comment]
Thanks. ☺️

Lets use a minor release bump here. (No removals or deprecations)

**Comment by mbeijen** [comment]
> Lets use a minor release bump here. (No removals or deprecations)

You mean to bump the last digit, which makes the version 0.27.1 instead of 0.28.0? (in 'semantic versioning', the last digit would be the patch level and the middle digit would be the minor level, ref https://semver.org/ - but I guess you're not using semver)

I've just updated the PR so now it's 0.27.1  - if there is anything else, please let me know

**Review by T-256 — APPROVED** [review]

**Comment by tomchristie** [comment]
> I guess you're not using semver

No and yes, in the lead up to a 1.0.

**Review by tomchristie — APPROVED** [review]

**Comment by tomchristie** [comment]
@encode/maintainers Could I get a review on this draft release https://github.com/encode/httpx/releases/tag/untagged-1f3c9bdb863e201ab647 - are we good to publish?

**Pull request merged**
