### PR TITLE
Add an indent to fix wrong rendering in warning block

### PR DESCRIPTION
**Pull request by SigureMo**
# Summary

Fix a wrong rendering in docs. https://www.python-httpx.org/async/

Before:

image

After:

image

# Checklist

- [ ] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [ ] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by zanieb** [comment]
Thanks for contributing!

This probably conflicts with #3049 cc @tomchristie

**Review by tomchristie — APPROVED** [review]

**Comment by tomchristie** [comment]
*"This branch is out-of-date with the base branch"* 🤔

**Comment by SigureMo** [comment]
> *"This branch is out-of-date with the base branch"* 🤔

I've just updated it.

**Comment by tomchristie** [comment]
Lovely, thanks

**Pull request merged**
