### PR TITLE
#453: Create new connection when stream space is exhausted

### PR DESCRIPTION
**Pull request by gdhameeja**

### CODE REVIEW

**Comment by tomchristie** [comment]
Apologies for not having gotten around to reviewing this just yet.

**Comment by gdhameeja** [comment]
No issues. I resolved the conflicts. Please review and let me know of any changes required.

**Comment by gdhameeja** [comment]
review please?

**Comment by tomchristie** [comment]
Looks reasonable yup, some conflicts to resolve.

I'd suggest we just keep the exception in `httpx/dispatch/base.py`, since it's a dispatch implementation detail, rather than something that we ever publicly expose.

**Comment by gdhameeja** [comment]
closing this PR since it seems `def send_headers` where the `NewConnectionRequired` was being raised has been changed.

**Comment by gdhameeja** [comment]
closing this PR since it seems `def send_headers` where the `NewConnectionRequired` was being raised has been changed.

**Pull request closed without merging**
