### PR TITLE
Add httpx-caching

### PR DESCRIPTION
**Pull request by sidharthv96**
The starting point for contributions should usually be [a discussion](https://github.com/encode/httpx/discussions)

Simple documentation typos may be raised as stand-alone pull requests, but otherwise
please ensure you've discussed your proposal prior to issuing a pull request.

This will help us direct work appropriately, and ensure that any suggested changes
have been okayed by the maintainers.

- [x] Initially raised as discussion https://github.com/encode/httpx/discussions/1693

### CODE REVIEW

**Comment by tomchristie** [comment]
Do we think we should wait until it has 0.18 compat? (Not sure, myself)

**Comment by sidharthv96** [comment]
The PR for 0.18 compat has been open for a few months now and last code commit was 4 months ago.

Adding it in the docs would be helpful mostly as a starting point because googling `httpx caching` doesn't bring that library up.

**Comment by sidharthv96** [comment]
I'll try to get a fork working with 0.18 and redis support in the coming weeks.

**Comment by tomchristie** [comment]
Ok. Let's get this in for now. Better than not having it linked, right?

**Comment by johtso** [comment]
Nice! Happy to get more eyes on this. Pull requests welcome!

Should only be a couple of tweaks to appease mypy and get the tests passing with 0.18. Will try and have a look over the next couple of days.

**Comment by johtso** [comment]
@tomchristie now working with 0.18 🎉

**Pull request merged**
