### PR TITLE
add socks5h proxy support

### PR DESCRIPTION
**Pull request by liubin**
In some case socks5h is needed to resolve the hostname.

# Summary

add socks5h proxy support.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.

### CODE REVIEW

**Comment by T-256** [comment]
`socks5` are resolving hostnames in remote side by default (socks5h).
Also, see [httpx-socks](https://github.com/romis2012/httpx-socks) where you can explicitly set `rdns=False` to locally resolving.

**Comment by liubin** [comment]
@T-256 Indeed I run into a complexity case that socks5 not work:

```bash
12:39:33-bin~/tmppp\ -> export https_proxy=socks5h://127.0.0.1:15666
12:39:49-bin~/tmppp\ -> curl -I https://twitter.com
HTTP/2 403 
date: Fri, 26 Apr 2024 04:39:51 GMT
perf: 7402827104
server: tsa_p
set-cookie: guest_id_marketing=v1%3A171410639188824760; Max-Age=63072000; Expires=Sun, 26 Apr 2026 04:39:51 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
set-cookie: guest_id_ads=v1%3A171410639188824760; Max-Age=63072000; Expires=Sun, 26 Apr 2026 04:39:51 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
set-cookie: personalization_id="v1_H5m2zAEnPFfEJv5Q0c4avQ=="; Max-Age=63072000; Expires=Sun, 26 Apr 2026 04:39:51 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
set-cookie: guest_id=v1%3A171410639188824760; Max-Age=63072000; Expires=Sun, 26 Apr 2026 04:39:51 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
x-powered-by: Express
... ...

12:39:51-bin~/tmppp\ -> export https_proxy=socks5://127.0.0.1:15666
12:39:56-bin~/tmppp\ -> curl -I https://twitter.com
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to twitter.com:443 
```

And my code with `requests` only work with socks5h too, if set to socks5, it will get an error:

```
  File "/Users/bin/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("SOCKSHTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /BAAI/bge-small-en-v1.5/resolve/main/config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))"), '(Request ID: a0fdd8ed-dd99-4b38-bf53-47f133004e22)')
```

My code using both requests and httpx, it is not controlled by me, but be the packages that I'm using directly.

So let httpx to support socks5h is the simplest way for my case.

**Comment by tomchristie** [comment]
Thanks, yep we probably should have `socks5h` proxy support.

Have you tested the above? I don't think it'll work, although you'll be able to pass `socks5h://` through, support for it isn't actually implemented in `httpcore` yet.

Here's where you'll actually need to start on this...

* A draft PR for `httpcore` adding [documentation for `sock5h` support](https://www.encode.io/httpcore/proxies/#socks-proxy-support).
* Update the PR to [implement the functionality](https://github.com/encode/httpcore/blob/master/httpcore/_sync/socks_proxy.py) as described in the docs.

**Comment by mateuszlitwin** [comment]
Hello @tomchristie! I am also running into this issue, i.e. lack of `socks5h://` support. I cannot use `socks5://` because it is interpreted different by other tools (e.g. curl). I did test this PR + 1 line change in  https://github.com/encode/httpcore/blob/master/httpcore/_models.py#L294 to add default port sock5h and it works as expected - traffic is sent to the proxy without resolving hostname.

**Comment by longouyang** [comment]
Hi @tomchristie - firstly, thanks so much for all the work you've done on this project. We sure use the library a lot at $DAYJOB.

Also - I'd be happy to pitch in $250 support to the project if we could get socks5h support merged.

**Review by tomchristie — APPROVED** [review]
Yep, thanks! Does also need an `httpcore` release in order to work all the way through.

**Comment by hawktang** [comment]
merge from https://github.com/encode/httpx/issues/3386

**Comment by hawktang** [comment]
When will the change for httpx and http core release to pip?

**Pull request merged**
