### PR TITLE
Make `name` in httpx.__init__ private

### PR DESCRIPTION
**Pull request by j178**
Prompted by https://github.com/encode/httpcore/pull/156/commits/35ecd2274faf1fdd4a6218bc07839d96b9791d7b

### CODE REVIEW

**Comment by jcugat** [comment]
Would be worth bringing [this test](https://github.com/encode/httpcore/pull/156/files#diff-b742918391873180aa8283b7dd4885d2) to httpx, since it's the one that surfaced the issue. Also, I'd use private variables `_*` instead of using `del`.

**Comment by j178** [comment]
@jcugat Thanks for reminding me! I added a test and reorder members in `__all__`.


> Also, I'd use private variables `_*` instead of using `del`.

I think these are just temporary variables, they will not be used anywhere, I prefer `del`ing them from the namespace.

**Comment by j178** [comment]
Updated.

**Comment by jcugat** [comment]
@tomchristie The test was added because one of the imports was not present inside `__all__`, and it's easy to forget to keep them synced. I don't understand what extra maintenance work that test is adding.

**Comment by tomchristie** [comment]
You're right sorry. I was taking a brief look on a phone screen, and it seemed a bit superfluous  But it's actually reasonable enough.

**Pull request merged**
