### PR TITLE
Set `open_connection` before adding the connection to `active_connections` (see https://github.com/encode/httpx/issues/689)

### LINKED ISSUE #689: Unexpected AssertionError (httpx 0.9.5)
I'm getting an unexpected `AssertionError` while trying to do a relatively simple `await client.get()` call.  Since the last time this worked I've done two big things, upgraded my project to use Python3.8 (not really important, but the assignment operator is useful for my project) as well as collapsing several httpx clients into a single, package-wide client, that is now being used to make several concurrent, but unrelated requests to the same host (FastAPI/Uvicorn, so no HTTP/2).

I'm not super familiar with the codebase, but at a quick glance it looks like this might be a problem with issuing the concurrent requests?  I can try to throw a lock around the requests to start, though I think that shouldn't really be necessary?

Not sure if it's useful, but the calling code is using uvloop and running on Linux (specifically the python:3.8 Docker container).

```
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 679, in get
    return await self.request(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 259, in request
    response = await self.send(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 403, in send
    response = await self.send_handling_redirects(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 465, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 591, in send_handling_auth
    response = await self.send_single_request(request, timeout, verify, cert)
  File "/opt/venv/lib/python3.8/site-packages/httpx/client.py", line 618, in send_single_request
    response = await dispatcher.send(
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 147, in send
    connection = await self.acquire_connection(
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 165, in acquire_connection
    connection = self.pop_connection(origin)
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 215, in pop_connection
    connection = self.active_connections.pop_by_origin(origin, http2_only=True)
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 46, in pop_by_origin
    if http2_only and not connection.is_http2:
  File "/opt/venv/lib/python3.8/site-packages/httpx/dispatch/connection.py", line 175, in is_http2
    assert self.open_connection is not None
AssertionError
```

I don't have a minimal example yet, I can try to put one together though if that'd be helpful.

### PR DESCRIPTION
**Pull request by kshramt**
Fixes #689

### CODE REVIEW

**Comment by kshramt** [comment]
Test code:

```
import asyncio
import httpx


def main():
    asyncio.run(run())


async def run():
    async with httpx.Client() as client:
        await asyncio.gather(*[runn(client, 20) for _ in range(20)])


async def runn(client, n):
    for _ in range(n):
        await run1(client)


def run1(client):
    return client.get(<URL>)


main()
```

**Comment by florimondmanca** [comment]
Edited the issue description to reference the original issue.

**Comment by tomchristie** [comment]
An alternate fix is to have `is_http2` return `False` if no connection has been acquired yet.

I'd *consider* leaning towards that instead. It's a lower footprint, and a less fundamental change than calling directly into `.connect` from the connection pool.

We've got some work remaining to do on dealing with stricter locking around the HTTPConnection state changes, and handling "this is a pending connection, that might (HTTP/2) or might not (HTTP/1.1) be able to support concurrent requests". (Draft PR #624) - I'm not sure that work would fit in so well with the "acquire the connection and wait until it's connected", because in the HTTP/2 case we'd like to be able to acquire a connection even if it's still in a PENDING state. (#514)

**Comment by florimondmanca** [comment]
Hmm, yes. I can confirm #700 fixes the original issue that this addresses with a much smaller footprint, so it seems we should consider it instead.

Still seems we don't have any test for the behavior of `hard_limit` with concurrent requests (esp. when using asyncio's `.gather()`), so I think we should add one eventually.

**Comment by tomchristie** [comment]
@kshramt Thanks for having put your time into this. Closing in favour of #700.

**Pull request closed without merging**
