### PR TITLE
Add compatibility differences with get, delete, head, options

### PR DESCRIPTION
**Pull request by jtmiclat**
Add compatibility differences with get, delete, head, and options.  

Relevant discussion: #395

### CODE REVIEW

**Comment by tomchristie** [comment]
I think(?) we actually have the same API as requests here, except in the `delete` case.
Where we disallow `files`/`data`/`json`, but `requests does not.

**Comment by jtmiclat** [comment]
@tomchristie requests actually allowed you to pass in the `json`, `files`, and `data` in all methods. It passed them as part of  `kwargs` to `api.request`. While for httpx, it was intentionallity not allowed.

Relevant link:
https://github.com/psf/requests/blob/master/requests/api.py

**Comment by tomchristie** [comment]
Ah yeah, so it does. Thanks for confirming!

**Comment by sethmlarson** [comment]
:tada: Thanks @jtmiclat! :tada:

**Pull request merged**
