### PR TITLE
Fast path returns for normalize_path cases

### PR DESCRIPTION
**Pull request by tomchristie**
Return early for cases where there are no `.` or `..` components in the path.

### CODE REVIEW

**Review by zanieb — APPROVED** [review]

**Comment by zanieb** [comment]
Did you do any microbenchmarks?

**Comment by tomchristie** [comment]
@zanieb good question.

**Comment by karpetrosyan** [comment]
It's a very small change, I think we can merge this without any microbenchmarks.

**Comment by tomchristie** [comment]
Okay, let's do that then.
It is still a good question. ☺️

**Pull request merged**
