### PR TITLE
Mount API

### PR DESCRIPTION
**Pull request by tomchristie**
Working towards having the proxy and transport configuration as part of a more generic URL mounting system.

Here's what I've done so far...

* Make `.transport` and `.proxies` private. We don't really want those as public API.
* A bit of cleanup in the `getproxies` code, for simplicity.
* A bit of refactoring in `transport_for_url` for simplicity.

### CODE REVIEW

**Comment by tomchristie** [comment]
Right, worth talking about this a bit, since it's a really fiddly one.

This PR drops `.transport` and `.proxies` in favour of a generic `._mounts`, which maps URL keys onto transport instances.

A URL like `https://www.google.com:1234` will attempt to match against the following URL keys, with this precedence...

* `https://www.google.com:1234`
* `all://www.google.com:1234`
* `https://www.google.com`
* `all://www.google.com`
* `https://*.google.com`
* `all://*.google.com`
* `https://*.com`
* `all://*.com`
* `https`
* `all`

The motivation of this change is that it...

Closes #1043, by supporting eg. `proxies={'all': '1.2.3.4', 'all://localhost': None}`
Closes #1039

**Comment by florimondmanca** [comment]
To be honest, dunno about this.

I think I need to read through #977 again to get the gist of the "mounting" idea.

- What would be a general design rule for mount keys?
- Currently we only have proxies and the connection pool as mounted transports, correct?
- Is there any similar idea implemented in an existing HTTP client? (Perhaps a non-Python even…)

**Comment by tomchristie** [comment]
> But to be honest, I'm in a "dunno about this" state for now.

I can understand that, yup.

Let's take this another way around then. A starting point for thinking about this is... https://requests.readthedocs.io/en/master/user/advanced/#transport-adapters

We'd like to support an equivalent functionality, although it's possible(?) that we want something slightly broader than straight-up prefix matching, since it'd be nice and consistent if we were able to fold the `NO_PROXY` behaviour into an equivalent mount-this-case-as-an-exclusion.

**Comment by tomchristie** [comment]
I'm going to see if I can take some smaller iterations onto *parts* that this is attempting to resolve, eg. looking at closing #1062 without introducing so much thrashing.

**Comment by tomchristie** [comment]
Superseeded by #1098, #1099, #1103

**Pull request closed without merging**
