### PR TITLE
Moved  create and verify ssl context function into the utils  and included  lru cache.

### PR DESCRIPTION
**Pull request by cansarigol**
Refs #978 

_globally caching our SSL contexts_ suggestion of @tomchristie .

### CODE REVIEW

**Comment by florimondmanca** [comment]
Hi @cansarigol, thanks for tackling this!

From what I can see, this PR tries to address both #978 and #983. It's probably best that we keep fixes for these separate. Most likely #983 is higher priority, as it would make `SSLConfig` go away (and this PR currently uses it for the other part).

**Comment by cansarigol** [comment]
Hi @florimondmanca , I thought that we can handle in a single PR and I can include a test about `SSLConfig().ssl_context == httpx.create_ssl_context()` .

**Comment by tomchristie** [comment]
Closing in favour of #996

**Comment by tomchristie** [comment]
Incidentally let's *not* jump straight in with implementing SSLContext caching once #996 is in. I think that aspect is worth *considering* but I don't think it's *necessarily* a given.

**Pull request closed without merging**
