### PR TITLE
Add branch coverage to report

### PR DESCRIPTION
**Pull request by StephenBrown2**
Adds `--cov-branch` to `setup.cfg` for pytest-cov to run branch coverage checks as well as line coverage. `--cov-branch` was added in [pytest-cov 2.5.0](https://pytest-cov.readthedocs.io/en/latest/changelog.html#id34).

This makes the coverage report a little more comprehensive, though secondary to line coverage, as even the [python devguide](https://devguide.python.org/coverage/#branch-coverage) says so:

> Testing every possible branch path through code, while a great goal to strive for, is a secondary goal to getting 100% line coverage...

As such, I'm not addressing the missing branch coverage in this PR, as I want to gauge the level of reception from the primary maintainers first.

Example output (run on master):

```
---------- coverage: platform darwin, python 3.7.4-final-0 -----------
Name                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------
httpx/__init__.py                            13      0      0      0   100%
httpx/__version__.py                          3      0      0      0   100%
httpx/api.py                                 21      0      0      0   100%
httpx/client.py                             204      0     46      0   100%
httpx/concurrency/__init__.py                 0      0      0      0   100%
httpx/concurrency/asyncio.py                146      1     34      4    97%   75, 47->exit, 72->75, 106->109, 121->111
httpx/concurrency/base.py                    63      0      0      0   100%
httpx/config.py                             153      3     54      5    95%   176-178, 93->100, 150->153, 172->175, 175->176, 191->exit
httpx/decoders.py                           103      0     20      1    99%   118->120
httpx/dispatch/__init__.py                    0      0      0      0   100%
httpx/dispatch/asgi.py                       76      0     14      1    99%   105->exit
httpx/dispatch/base.py                       24      0      0      0   100%
httpx/dispatch/connection.py                 75      0     18      1    99%   115->exit
httpx/dispatch/connection_pool.py           102      0     18      2    98%   51->53, 133->136
httpx/dispatch/http11.py                     90      0     14      0   100%
httpx/dispatch/http2.py                     125      2     36      3    97%   197-201, 160->157, 175->169, 216->exit
httpx/dispatch/threaded.py                   34      0      4      0   100%
httpx/dispatch/wsgi.py                       60      0     16      0   100%
httpx/exceptions.py                          25      0      0      0   100%
httpx/middleware/__init__.py                  0      0      0      0   100%
httpx/middleware/base.py                      4      0      0      0   100%
httpx/middleware/basic_auth.py               15      0      0      0   100%
httpx/middleware/custom_auth.py               9      0      0      0   100%
httpx/middleware/redirect.py                 68      0     27      0   100%
httpx/models.py                             695      0    306     15    99%   588->590, 690->exit, 739->746, 841->848, 843->848, 852->856, 865->870, 911->913, 1135->1134, 1136->1134, 1137->1134, 1157->1156, 1158->1156, 1159->1156, 1171->1173
httpx/multipart.py                           72      0     22      0   100%
httpx/status_codes.py                        87      0      2      0   100%
httpx/utils.py                              101      0     46      2    99%   78->81, 84->87
tests/client/__init__.py                      0      0      0      0   100%
tests/client/test_async_client.py            99      0      4      0   100%
tests/client/test_auth.py                    71      0      0      0   100%
tests/client/test_client.py                 113      0      8      0   100%
tests/client/test_cookies.py                 64      0      4      1    99%   27->exit
tests/client/test_headers.py                 46      0      2      1    98%   28->exit
tests/client/test_properties.py              13      0      0      0   100%
tests/client/test_redirects.py              194      0     36      2    99%   214->exit, 229->exit
tests/concurrency.py                          8      0      0      0   100%
tests/conftest.py                           128      0     20      0   100%
tests/dispatch/__init__.py                    0      0      0      0   100%
tests/dispatch/test_connection_pools.py      99      0      0      0   100%
tests/dispatch/test_connections.py           23      0      0      0   100%
tests/dispatch/test_http2.py                 89      0      0      0   100%
tests/dispatch/test_threaded.py              59      0     10      0   100%
tests/dispatch/utils.py                      99      0     30      3    98%   79->78, 100->102, 115->118
tests/models/__init__.py                      0      0      0      0   100%
tests/models/test_cookies.py                 37      0      0      0   100%
tests/models/test_headers.py                 94      0      0      0   100%
tests/models/test_queryparams.py             39      0      0      0   100%
tests/models/test_requests.py                57      0      4      0   100%
tests/models/test_responses.py              189      0     16      0   100%
tests/models/test_url.py                     91      0      2      0   100%
tests/test_api.py                            43      0      0      0   100%
tests/test_asgi.py                           63      0      2      0   100%
tests/test_concurrency.py                    18      0      0      0   100%
tests/test_config.py                        119     14      0      0    88%   183-204
tests/test_decoders.py                       92      0      2      0   100%
tests/test_multipart.py                      69      0      0      0   100%
tests/test_status_codes.py                   10      0      0      0   100%
tests/test_timeouts.py                       25      0      0      0   100%
tests/test_utils.py                          40      0      2      0   100%
tests/test_wsgi.py                           55      0      2      0   100%
-------------------------------------------------------------------------------------
TOTAL                                      4514     20    821     41    99%
```

### CODE REVIEW

**Comment by sethmlarson** [comment]
I think we should be doing branch coverage, so I'm :+1: on this moving forward. :)

**Comment by StephenBrown2** [comment]
I can, but my time is limited, so it may be a while.

**Comment by tomchristie** [comment]
My general take on this is that 100% line coverage is an actionable metric, and that branch coverage isn't directly actionable enough to be worth adding vs. the extra noise that it adds.

I'd likely be okay with us being able to see it, but I don't think we likely want it by default.

(Also a case where I'd want to be convinced to be doing something across the board for all encode projects, and I don't think this makes the cut-off from my POV)

**Comment by sethmlarson** [comment]
Let's defer this until we get our coverage to 100%, then we can reconsider.  Thanks @StephenBrown2!

**Comment by StephenBrown2** [comment]
Good enough by me. When I have more time to put into it I'll submit another PR that adds tests for all the branch coverage that seems reasonable.

**Pull request closed without merging**
