### PR TITLE
Version 0.16.1

### PR DESCRIPTION
**Pull request by tomchristie**
### Fixed

* Support literal IPv6 addresses in URLs. (Pull #1349)
* Force lowercase headers in ASGI scope dictionaries. (Pull #1351)

### CODE REVIEW

**Comment by bdieng-sudo** [comment]
appying the httpx version =>0.16.1 here 1.0.5 still not correct the occuring :
"raise to_exc(exc) from None
httpcore.ConnectError: [Errno -2] Name or service not known"

what's going wrong?

**Comment by tomchristie** [comment]
@bdieng-sudo Couldn't really say from that alone. I'd suggest start a discussion, and include a bit more information about what you're actually doing. Someone will probably be able to help you out a bit if you do that.

**Comment by tomchristie** [comment]
>  I'd suggest start a discussion, and include a bit more information about what you're actually doing.

I'd suggest using the "discussions" feature in the future...

Screenshot 2021-05-10 at 14 52 19

> httpx.ConnectError: [Errno -2] Name or service not known

Most likely you're attempting to make a request to an invalid URL.

This... `http://api:5000` looks wrong to me.

**Comment by bdieng-sudo** [comment]
that's the question.
the API:5000 is defined s a container as shown in the "podman ps -a" cmd
(env) hana03:~/shaman-next # podman ps -a
CONTAINER ID  IMAGE                                  COMMAND               CREATED       STATUS                 PORTS                                                                     NAMES
0bc8e8e93bd6  docker.io/hashicorp/http-echo:latest   -text=hello           26 hours ago  Up 26 hours ago                                                                                  serv
907b6812eda1  docker.io/library/mongo:4.0            mongo --host mong...  4 days ago    Exited (0) 3 days ago  0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  mongo_init
10babde1f18c  docker.io/library/redis:latest         redis-server          4 days ago    Up 4 days ago          0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  redis
cf74d6adcb87  docker.io/sphrbthyk/shaman-api:latest  uvicorn shaman_ap...  4 days ago    Up 4 days ago          0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  api
e7903da84873  docker.io/sphrbthyk/shaman-ui:latest   npm run start         4 days ago    Up 4 days ago          0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  ui
37b5e7c5de95  docker.io/library/mongo:4.0            mongod --bind_ip ...  4 days ago    Up 3 days ago          0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  mongo
79770c21b1bd  k8s.gcr.io/pause:3.2                                         4 days ago    Up 4 days ago          0.0.0.0:5001->5000/tcp, 0.0.0.0:27020->27017/tcp, 0.0.0.0:3000->3000/tcp  fbc8f144584c-infra
(env) hana03:~/shaman-next #

**Comment by bdieng-sudo** [comment]
this join your diagnostic Tom.
when simply run "curl http://api:5000"
........
........
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://api:5000/">http://api:5000/</a></p>

<blockquote id="error">
<p><b>Unable to determine IP address from host name <q>api</q></b></p>
</blockquote>

<p>The DNS server returned:</p>
<blockquote id="data">
<pre>Name Error: The domain name does not exist.</pre>
</blockquote>

<p>This means that the cache was not able to resolve the hostname presented in the URL. Check if the address is correct.</p>

**Pull request merged**
